# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Xilinx_Vivado_SDK_2019.1_0524_1430/project/RISCV32ICPU/RISCV32ICPU.srcs/sources_1/ip/bram_img1r/bram_img1r.xci
# IP: The module: 'bram_img1r' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Xilinx_Vivado_SDK_2019.1_0524_1430/project/RISCV32ICPU/RISCV32ICPU.srcs/sources_1/ip/bram_img1r/bram_img1r_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_img1r'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Xilinx_Vivado_SDK_2019.1_0524_1430/project/RISCV32ICPU/RISCV32ICPU.srcs/sources_1/ip/bram_img1r/bram_img1r.xci
# IP: The module: 'bram_img1r' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Xilinx_Vivado_SDK_2019.1_0524_1430/project/RISCV32ICPU/RISCV32ICPU.srcs/sources_1/ip/bram_img1r/bram_img1r_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_img1r'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
